services:
  - type: web
    name: watchparty
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 10000
      - key: BACKEND_PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
