services:
  - type: web
    name: watchparty
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 10000
      - key: BACKEND_PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true

  - type: web
    name: watchparty-janus-audio
    runtime: docker
    dockerfilePath: ./audio-server/Dockerfile
    dockerContext: ./audio-server
    envVars:
      - key: JANUS_PUBLIC_IP
        value: 0.0.0.0
      - key: JANUS_STUN_SERVER
        value: stun:stun.l.google.com:19302
